services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/symfony
    environment:
      DATABASE_URL: "pgsql://symfony:symfony@db:5432/pokemon_db"

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
      POSTGRES_DB: pokemon_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
